[metadata]
name = pre-commit-bigfix
version = attr: pre_commit_bigfix.__version__
author = JGStew
author_email = noreply@jgstew.com
description = pre-commit hooks for BigFix content
keywords = pre-commit hooks python bigfix bes
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/jgstew/pre-commit-bigfix
project_urls =
    Bug Tracker = https://github.com/jgstew/pre-commit-bigfix/issues
    Source = https://github.com/jgstew/pre-commit-bigfix
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers

[options]
package_dir =
    = .
packages = pre_commit_bigfix
python_requires = >=3.8
include_package_data = True
install_requires =
    lxml
    validate_bes_xml

[options.package_data]
pre_commit_bigfix = schclass_data/*.schclass

[options.extras_require]
test =
    pytest

[options.entry_points]
console_scripts =
    bes-schema-validate = pre_commit_bigfix.bes_schema_validate:main
    # deprecated alias for bes-schema-validate (same function)
    validate-bes = pre_commit_bigfix.bes_schema_validate:main
    check-bes-conventions = pre_commit_bigfix.bigfix_bes_check_conventions:main
    bes-actionscript-lint-schclass = pre_commit_bigfix.bes_actionscript_lint_schclass:main
